TRY/CATCH

Es algo muy sabido que Javascript en la espicificacion ES3, especificaba la declaracion de la variable
en el catch clause, de un try/catch para ser blocked scoped, al block the catch.
Por instancia:

try {
    undefined(); //illegal operation for force an aception.
}
catch(err) {
    console.log(err); // works
}

console.log(err); // RefferError: `err` not found

Como usted puede ver, err solo existe en clause de catch, y envia un error cuando usted trata
de referenciarla en otro lado.

